import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          {/* <Toaster /> Moved to Dashboard to prevent login blocking */}
          <div className="fixed top-0 left-0 w-full bg-red-600 text-white text-center font-bold py-2 z-[99999]">
            ⚠️ SYSTEM UPDATE: v1.4 - GLOBAL BLUE MODE (Refreshed at {new Date().toLocaleTimeString()})
          </div>
          <div className="fixed bottom-1 right-1 bg-black text-white text-[10px] px-1 rounded opacity-50 pointer-events-none z-50">
            v1.4 (Dark Mode)
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
